version: 2

sources:
  - name: airbnb_project
    schema: airbnb
    tables:
      - name: listings
        identifier: listingss
      - name: hosts
        identifier: hostss
      - name: reviews
        identifier: reviewss
        loaded_at_field: date
        freshness:
          warn_after: {count: 1, period: hour}
          error_after: {count: 24, period: hour}
          
